const express = require("express");
const env = require("../config/env");
const authRoutes = require("./auth.routes");
const usersRoutes = require("./users.routes");
const profilesRoutes = require("./profiles.routes");
const familyRoutes = require("./family.routes");
const mediaRoutes = require("./media.routes");
const preferencesRoutes = require("./preferences.routes");
const privacyRoutes = require("./privacy.routes");
const searchRoutes = require("./search.routes");
const matchesRoutes = require("./matches.routes");
const interestsRoutes = require("./interests.routes");
const conversationsRoutes = require("./conversations.routes");
const messagesRoutes = require("./messages.routes");
const notificationsRoutes = require("./notifications.routes");
const contactsRoutes = require("./contacts.routes");
const secureConnectRoutes = require("./secure-connect.routes");
const subscriptionsRoutes = require("./subscriptions.routes");
const paymentsRoutes = require("./payments.routes");
const boostsRoutes = require("./boosts.routes");
const referralsRoutes = require("./referrals.routes");
const verificationsRoutes = require("./verifications.routes");
const reportsRoutes = require("./reports.routes");
const rmRoutes = require("./rm.routes");
const adminRoutes = require("./admin.routes");
const publicRoutes = require("./public.routes");
const healthRoutes = require("./health.routes");
const errorPagesRoutes = require("./error-pages.routes");

const router = express.Router();

router.use("/health", healthRoutes);
router.use("/errors", errorPagesRoutes);
router.use(env.apiPrefix + "/auth", authRoutes);
router.use(env.apiPrefix + "/users", usersRoutes);
router.use(env.apiPrefix + "/profiles", profilesRoutes);
router.use(env.apiPrefix + "/family", familyRoutes);
router.use(env.apiPrefix + "/media", mediaRoutes);
router.use(env.apiPrefix + "/preferences", preferencesRoutes);
router.use(env.apiPrefix + "/privacy", privacyRoutes);
router.use(env.apiPrefix + "/search", searchRoutes);
router.use(env.apiPrefix + "/matches", matchesRoutes);
router.use(env.apiPrefix + "/interests", interestsRoutes);
router.use(env.apiPrefix + "/conversations", conversationsRoutes);
router.use(env.apiPrefix + "/messages", messagesRoutes);
router.use(env.apiPrefix + "/notifications", notificationsRoutes);
router.use(env.apiPrefix + "/contacts", contactsRoutes);
router.use(env.apiPrefix + "/secure-connect", secureConnectRoutes);
router.use(env.apiPrefix + "/subscriptions", subscriptionsRoutes);
router.use(env.apiPrefix + "/payments", paymentsRoutes);
router.use(env.apiPrefix + "/boosts", boostsRoutes);
router.use(env.apiPrefix + "/referrals", referralsRoutes);
router.use(env.apiPrefix + "/verifications", verificationsRoutes);
router.use(env.apiPrefix + "/reports", reportsRoutes);
router.use(env.apiPrefix + "/rm", rmRoutes);
router.use(env.apiPrefix + "/admin", adminRoutes);
router.use(env.apiPrefix + "/public", publicRoutes);

module.exports = router;
